# Generated by Django 4.0 on 2021-12-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
